version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-75-246-118.eu-west-1.compute.amazonaws.com
            database: dbak9nddg3quka
            user: klggdglpaejwpu
            password: 2ed6b3e0f90187e0a4993284301b59daa1137f771756198e4cf031188cdb3d8a
            ssl: true
            rawAccess: true
            port: 5432
            migrations: true
#  postgres:
#    image: postgres
#    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    # ports:
    # - "5432:5432"
#    environment:
#      POSTGRES_USER: jxkrlcoapcpqgi
#      POSTGRES_PASSWORD: e9d6400125115c6f0d0211d739a44c199f0b1fc3a1eef42182eab2560982854c
#    volumes:
#      - postgres:/var/lib/postgresql/data
#volumes:
#  postgres:
